import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero.tsx'
import NavBar from '../components/NavBar.tsx'

export default function Home() {
  return (
    <div style={{ background: '#FEF4EA'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
            rel="preload"
            href="/fonts/Söhne-Buch.ttf"
            as="font"
            crossOrigin=""
          />
        <link
            rel="preload"
            href="/fonts/Söhne-Kräftig.ttf"
            as="font"
            crossOrigin=""
          />
      </Head>
      <NavBar />

      <Hero />

    </div>
  )
}
